/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import tpc.finalproject.Account;
import tpc.finalproject.AccountManager;
import tpc.finalproject.Color;
import tpc.finalproject.Employee;
import tpc.finalproject.EmployeeManager;
import tpc.finalproject.Material;
import tpc.finalproject.SubstrateType;

/**
 *
 * @author damanglez
 */
public class HomeForm extends JFrame {
	private AccountManager accountManager;
	private EmployeeManager employeeManager;

    /**
     * Creates new form HomeForm
     */
    public HomeForm() {
        initComponents();
		accountManager = new AccountManager();
		employeeManager = new EmployeeManager();
		
		// we refresh all atbles
		refresh();
    }
	
	/**
	 * 
	 */
	private void refresh() {
		// accounts
		refreshAccounts();
		refreshEmployees();
	}
	
	/**
	 * Prints all accounts in table
	 */
	private void refreshAccounts() {
		DefaultTableModel tm = (DefaultTableModel)accountsTable.getModel();
		tm.getDataVector().removeAllElements();
		accountManager.list().forEach((acc) -> {
			tm.addRow(new Object[] { acc.getId(), acc.getName(),
				acc.getContactName(), acc.getPhoneNumber(), acc.getContactEmail() });
		});
	}

	/**
	 * Prints all accounts in table
	 */
	private void refreshEmployees() {
		DefaultTableModel tm = (DefaultTableModel)employeesTable.getModel();
		tm.getDataVector().removeAllElements();
		employeeManager.list().forEach((emp) -> {
			tm.addRow(new Object[] { emp.getId(), emp.getFirstName(),
				emp.getLastName(), emp.getPhoneNumber(), emp.getDepartment()});
		});
	}	

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        accountsTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        employeesTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        accountsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Contact Name", "Phone", "Department"
            }
        ));
        jScrollPane1.setViewportView(accountsTable);
        accountsTable.getAccessibleContext().setAccessibleName("tabAccountHome");

        jTabbedPane1.addTab("Account", jScrollPane1);

        employeesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Department", "Phone", "E-mail"
            }
        ));
        jScrollPane2.setViewportView(employeesTable);
        employeesTable.getAccessibleContext().setAccessibleName("tabEmployeeHome");

        jTabbedPane1.addTab("Employee", jScrollPane2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Substrate Type", "Color", "Dimensions"
            }
        ));
        jScrollPane3.setViewportView(jTable3);
        jTable3.getAccessibleContext().setAccessibleName("tabMaterialHome");

        jTabbedPane1.addTab("Material", jScrollPane3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Account", "Due Date", "Machine", "Method", "Substrate", "Produce By", "Revised By"
            }
        ));
        jScrollPane4.setViewportView(jTable4);
        jTable4.getAccessibleContext().setAccessibleName("tabWOHome");

        jTabbedPane1.addTab("Work Order", jScrollPane4);

        jButton1.setText("New");
        jButton1.setMaximumSize(new java.awt.Dimension(63, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(63, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(63, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Edit");
        jButton3.setMaximumSize(new java.awt.Dimension(63, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(63, 23));
        jButton3.setPreferredSize(new java.awt.Dimension(63, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Exit");
        jButton4.setMaximumSize(new java.awt.Dimension(63, 23));
        jButton4.setMinimumSize(new java.awt.Dimension(63, 23));
        jButton4.setPreferredSize(new java.awt.Dimension(63, 23));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("THE PRINTER'S SYSTEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton2)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("tabHome");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");
        jButton1.getAccessibleContext().setAccessibleName("btmNewHome");
        jButton1.getAccessibleContext().setAccessibleDescription("");
        jButton2.getAccessibleContext().setAccessibleName("btmDeleteHome");
        jButton3.getAccessibleContext().setAccessibleName("btmEditHome");
        jButton4.getAccessibleContext().setAccessibleName("btmHomeExit");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JDialog fr = null;
		int tabSelectIndex = jTabbedPane1.getSelectedIndex();
        
        switch (tabSelectIndex) {
            case 0:
                Account newAccount = new Account(accountManager.getNextId(), 
						null, null, null, null, null, null, null, null, null);
                fr = new AccountForm(newAccount, accountManager, true);
                break;
            case 1: 
                Employee newEmployee = new Employee(employeeManager.getNextId(), 
						null, null, null, null, null);
                fr = new EmployeeForm(newEmployee, employeeManager, true);
                break;
            case 2:
                Material material = new Material(0, null, 
                        SubstrateType.NONE, Color.WHITE, 0, 0, 0);
                fr = new MaterialForm(material);
                break;
			default:
                fr = new WorkOrderForm();
                break;
        }
		
		fr.addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosed(WindowEvent e) {
				refresh();
			}
		});
		fr.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		JDialog fr = null;
		int selection;
		int tabSelectIndex = jTabbedPane1.getSelectedIndex();
		
		switch (tabSelectIndex) {
            case 0:
                selection = accountsTable.getSelectedRow();
				if (selection != -1)
					fr = new AccountForm(accountManager.get(selection),
						accountManager, false);
				 
				break;
            case 1: 
				selection = employeesTable.getSelectedRow();
				if (selection != -1)
					fr = new EmployeeForm(employeeManager.get(selection),
						employeeManager, false);
				
                break;
            case 2:
                Material material = new Material(0, null, 
                        SubstrateType.NONE, Color.WHITE, 0, 0, 0);
                fr = new MaterialForm(material);
                break;
			default:
                fr = new WorkOrderForm();
                break;
        }
		
		if (fr != null) {
			fr.addWindowListener(new WindowAdapter() {
				@Override
				public void windowClosed(WindowEvent e) {
					refresh();
				}
			});
			fr.setVisible(true);
		}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		int selection;
		int tabSelectIndex = jTabbedPane1.getSelectedIndex();
		
		switch (tabSelectIndex) {
            case 0:
                selection = accountsTable.getSelectedRow();
				if (selection != -1) {
					accountManager.remove(selection);
					accountManager.save();
					refresh();
				}
				break;
            case 1: 
				selection = employeesTable.getSelectedRow();
				if (selection != -1) {
					employeeManager.remove(selection);
					employeeManager.save();
					refresh();
				}
                break;
            case 2:
                
                break;
			default:
                
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accountsTable;
    private javax.swing.JTable employeesTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
